### ISSUE TITLE
Choc switch cutout

### ISSUE THREAD

**Issue by pujvz** [keebio/kb-plategen#4]
I am attempting to build a keyboard based on the cepstrum. The plate generator does not appear to have an option for choc switch cutout. I would like to request this feature.

**Comment by nooges** [comment]
The Choc switch cutout is the same size as the MX one (14x14mm).On May 14, 2023, at 4:04 PM, pujvz ***@***.***> wrote:﻿
I am attempting to build a keyboard based on the cepstrum. The plate generator does not appear to have an option for choc switch cutout. I would like to request this feature.

**Comment by pujvz** [comment]
Oops, sorry I am new to this. Thanks for the clarification @nooges . Closing this.
